In [1]:
import numpy as np

# QUES 1
Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [3]:
arr=np.array([1,2,3,6,4,5])

In [4]:
b=np.flip(arr)
print(b)
#Using Slicing
c=arr[::-1]
print(c)

[5 4 6 3 2 1]
[5 4 6 3 2 1]


# QUES 2
 Compare the following numpy arrays: 
 
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [6]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])

In [7]:
#Method 1
if np.array_equal(arr1,arr2):
    print('equal')
else:
    print('not equal')

equal


In [8]:
#Method 2
# This method first compares arrays element-wise using ==, then checks if all results are True with .all().
dif = arr1 == arr2
b = dif.all()
print(b)

True


# QUES 3
Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [10]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

In [11]:
#using bincount(restricted method,only int allowed,list can get very big)
xbincount=np.bincount(x)
print(xbincount)
ybincount=np.bincount(y)
print(ybincount)
xmax=np.argmax(xbincount)
print(xmax,np.where(xmax))

[0 5 2 1 1 1]
[0 3 2 3 2]
1 (array([0], dtype=int64),)


C:\Users\bhoom\AppData\Local\Temp\ipykernel_42452\1784897627.py:7: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  print(xmax,np.where(xmax))


In [12]:
#method 2
def most_freq_value(x=np.array([1,2,3,4,5,1,2,1,1,1])):
    num1,count1=np.unique(x,return_counts=True)
    freq1=zip(num1,count1)
    print("The unique numbers and their frequencies are: ", dict(freq1))
most_freq_value()
most_freq_value([1,1,1,2,3,4,2,4,3,3])

The unique numbers and their frequencies are:  {1: 5, 2: 2, 3: 1, 4: 1, 5: 1}
The unique numbers and their frequencies are:  {1: 3, 2: 2, 3: 3, 4: 2}


# QUES 4
For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 

i. Sum of all elements 

ii.Sum of all element’s row-wise 

iii.Sum of all element’s column-wise

In [14]:
def find_sums(gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')):
    print("Sum of all elements is: ",gfg.sum())
    print("Sum of all elements row-wise: \n",gfg.sum(axis=1))
    print("Sum of all elements column-wise: ",gfg.sum(axis=0))
    #method 2
    #gfg1=np.array([[4,1,9],[12,3,1],[4,5,6]])
    #print(gfg1)
    #print("Sum of all the elements is: ", gfg1.sum())
    #print("Sum of row wise elements is: ", gfg1.sum(axis=1))
    #print("Sum of column wise elements is: ", gfg1.sum(axis=0))
find_sums()

Sum of all elements is:  45
Sum of all elements row-wise: 
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:  [[20  9 16]]
